//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::Type;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "set_operation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub left_operand_id: i32,
    pub right_operand_id: i32,
    pub r#type: Type,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::set::Entity",
        from = "Column::LeftOperandId",
        to = "super::set::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Set2,
    #[sea_orm(
        belongs_to = "super::set::Entity",
        from = "Column::RightOperandId",
        to = "super::set::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Set1,
}

impl ActiveModelBehavior for ActiveModel {}
